services:
  php:
    build:
      context: ./docker/php
    container_name: symfony_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data: