services:
  php:
    build:
      context: ./docker/php
    container_name: symfony_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - app_network
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app_network

networks:
  app_network: